In [1]:
import numpy as np
from random import randint

1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
a = np.array([randint(0, 10) for i in range(20)], dtype=int)
a

array([ 3,  5,  5, 10,  2,  2,  1,  1,  4,  8,  9,  5, 10,  1,  4,  5,  2,
        8,  5,  0])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [3]:
a = np.array(
    [
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]
    ],
        dtype=int)
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

3. Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [4]:
a = np.random.randint(1, 11, size=(5, 5))
a

array([[ 2,  5,  6,  9,  3],
       [10,  3,  3,  7,  8],
       [ 3,  4, 10,  8,  7],
       [ 5,  2,  9, 10,  2],
       [ 2,  6,  3,  7,  4]])

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
a = np.random.rand(4, 4)
a

array([[0.0649318 , 0.0464773 , 0.90151488, 0.4663348 ],
       [0.89408946, 0.51696   , 0.37531906, 0.49269704],
       [0.84588599, 0.77386286, 0.24376816, 0.22334534],
       [0.51892771, 0.17980068, 0.43369021, 0.81266013]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
a = np.random.randint(1, 11, size=(5, 5))
b = np.random.randint(1, 11, size=(5, 5))
print(f"addition operation:\n{a + b}")
print(f"subtraction operation:\n{a - b}")
print(f"multiplication operation:\n{a * b}")

addition operation:
[[14 17 12 13  8]
 [10 16 16 16  8]
 [14 14 11  7 18]
 [13  8 15 12 10]
 [ 7  8 13  2  9]]
subtraction operation:
[[ 4  3  6  7 -6]
 [ 4 -2  0  2 -6]
 [-4 -2  1 -1  2]
 [-1 -6 -3  4  8]
 [-3  4 -3  0  1]]
multiplication operation:
[[45 70 27 30  7]
 [21 63 64 63  7]
 [45 48 30 12 80]
 [42  7 54 32  9]
 [10 12 40  1 20]]


6. Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.


In [7]:
a = np.random.randint(1, 11, size=7)
b = np.random.randint(1, 11, size=7)
np.dot(a, b)

175

7. Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [8]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
np.dot(a, b)

array([[16, 30, 10],
       [36, 42, 18]])

8. Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [9]:
a = np.random.randint(1, 11, size=(3, 3))
np.linalg.inv(a)

array([[ 0.13445378, -0.02941176,  0.01260504],
       [-0.03361345,  0.13235294, -0.12815126],
       [-0.00840336, -0.02941176,  0.15546218]])

9. Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [10]:
a = np.random.rand(4, 4)
np.transpose(a)

array([[0.27441882, 0.67712478, 0.80946605, 0.69295879],
       [0.78733974, 0.5988494 , 0.7185741 , 0.40838309],
       [0.81000479, 0.00580627, 0.55685216, 0.47545272],
       [0.48585562, 0.95672864, 0.78014424, 0.24780643]])

10. Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [11]:
a = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=4)
np.dot(a, vector)

array([59, 89, 86])

11. Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [12]:
a = np.random.rand(2, 3)
b = np.random.rand(3)

np.dot(a, b)

array([0.40419936, 0.12838983])

12. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [13]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

np.multiply(a, b)

array([[25, 20],
       [24, 54]])

13. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [14]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))

np.dot(a, b)

array([[105,  63],
       [117,  71]])

14. Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [15]:
a = np.random.randint(1, 101, size=(5, 5))

np.sum(a)

1229

15. Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [16]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))

np.subtract(a, b)

array([[-4, -5, -7,  0],
       [ 6,  1,  4, -1],
       [ 5,  9, -1, -4],
       [-5, -4, -5,  2]])

16. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [17]:
a = np.random.rand(3, 3)

np.sum(a, axis=1, keepdims=True)

array([[0.54826093],
       [1.8155362 ],
       [1.44064816]])

17. Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [18]:
a = np.random.randint(1, 11, size=(3, 4))

np.square(a)

array([[ 49,  64,  25,  64],
       [100,  81,  25, 100],
       [100,  64,   4,   4]])

18. Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [19]:
a = np.random.randint(1, 51, size=4)

np.sqrt(a)

array([2.        , 5.56776436, 4.79583152, 5.91607978])